openapi: 3.0.0
info:
  title: cv-builder API developed by Meshack Mbuvi for fun
  summary: API endpoints for CV_BUILDER API
  description: Please select the serve below depending on whether you are using Heroku or running the application locally

version: 0.1.9

servers:
  - url: http://localhost:3000/v1

components:
  securitySchemes:
    user-key:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: 1
        firstName:
          type: string
          example: Lannucci
        lastName:
          type: string
          example: Lannucci
        password:
          type: string
          example: test
        email:
          type: string
          example: test@gmail.com
    Employment:
      type: object
      properties:
        title:
          type: string
          example: test
        employer:
          type: string
        city:
          type: string
        startDate:
          type: string
        endDate:
          type: string
        description:
          type: string
paths:
  /users/signup:
    post:
      summary: create new user account
      description: creates a new account for the user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  example: Lannucci
                lastName:
                  type: string
                  example: Lannucci
                password:
                  type: string
                  example: test
                email:
                  type: string
                  example: test@gmail.com

      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  rows:
                    $ref: "#components/schemas/User"
  /users/login:
    post:
      summary: Login a user
      description: Endpoint for user login
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: test
                email:
                  type: string
                  example: test@gmail.com

      responses:
        200:
          description: User logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      firstName:
                        type: string
                        example: Lannucci
                      lastName:
                        type: string
                        example: Lannucci
                      email:
                        type: string
                        example: test@example.com
                      accountType:
                        type: string
                        example: normal
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                  accessToken:
                    type: string
                  expires_in:
                    type: string
  /employments/new:
    post:
      summary: Create new employment history
      tags:
        - Employment
      security:
        - {}
        - user-key: []

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: test
                employer:
                  type: string
                city:
                  type: string
                startDate:
                  type: string
                endDate:
                  type: string
                description:
                  type: string

      responses:
        201:
          description: New employment history created
          content:
            application/json:
              schema:
                type: object
                properties:
                  $ref: "#components/schemas/Employment"
                  message:
                    type: string
